aspect_ratio = 1.0
image_width = 500
image_height = 500
image_scale = 0.01724138
output_path = 'output.png'
samples_per_pixel = 58
max_depth = 50
scene_index = 11
seed = 9873651359645
use_loop_rendering = false
