aspect_ratio = 1.0
image_width = 500
image_height = 500
image_scale = 0.25
output_path = 'output.png'
subpixels_per_pixel = 16
samples_per_pixel = 4
max_depth = 50
scene_index = 1
seed = 9873651359645
use_loop_rendering = true
